name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build NPM package, run lint analysis and tests
      run: |
        npm install
        npm run lint
        npm run test
      env:
        CI: true
